import Image from "next/image";
import { useState, useEffect } from "react";
import { motion } from "framer-motion";

const PROMPTS = [
  { label: "Boris's experience?", icon: "/about.svg" },
  { label: "Current role and contributions", icon: "/dashboard.svg" },
  { label: "Skills and strengths", icon: "/fork.svg" },
  { label: "Contact and availability", icon: "/json.svg" },
];

// 1. PARSER — detects special tags and returns structured data
function parseResponse(text) {
  const timelineMatch = text.match(/<TIMELINE>([\s\S]*?)<\/TIMELINE>/);
  if (timelineMatch) {
    try {
      const jobs = JSON.parse(timelineMatch[1].trim());
      const summary = text.replace(/<TIMELINE>[\s\S]*?<\/TIMELINE>/, "").trim();
      return { type: "timeline", jobs, summary };
    } catch {}
  }

  // extract any <LINK> tags from text responses
  const links = [];
  const linkRegex = /<LINK>(.*?)<\/LINK>/g;
  let match;
  while ((match = linkRegex.exec(text)) !== null) {
    links.push(match[1]);
  }
  const cleanText = text.replace(/<LINK>.*?<\/LINK>/g, "").trim();

  return { type: "text", content: cleanText, links };
}

// 2. TIMELINE COMPONENT
function Timeline({ jobs, summary }) {
  return (
    <div>
      <div>
        <h3>Experience timeline</h3>
        <p>
          Here's a summary a career history based on the information provided.
        </p>
      </div>
      <div className="timeline">
        {jobs.map((job, i) => (
          <div key={i} className="timeline-item-chat">
            <small className="timeline-period">{job.period}</small>
            <div className="timeline-content">
              <strong>{job.role}</strong>
              <a href={job.website} target="_blank" rel="noreferrer">
                {job.company}
              </a>
            </div>
          </div>
        ))}
      </div>
      {summary && <p className="timeline-summary">{summary}</p>}
    </div>
  );
}

// LinkCard component to display links in text answers

function LinkCard({ url }) {
  const display = url.replace(/^https?:\/\//, "");

  return (
    <a href={url} target="_blank" rel="noreferrer" className="link-card">
      <div className="flex flex-center">
        <Image
          src="/web.svg"
          alt="Link"
          width={24}
          height={24}
          className="side-button"
        />
        <span className="link-card-url">{display}</span>
      </div>
      <span className="link-card-icon">↗</span>
    </a>
  );
}

// 3. CHAT MODE — ties it all together
export default function ChatMode() {
  const [answer, setAnswer] = useState(null);
  const [loading, setLoading] = useState(false);
  const [active, setActive] = useState(null);

  async function ask(question) {
    setActive(question);
    setLoading(true);
    setAnswer(null);

    const res = await fetch("/api/chat", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ question }),
    });
    const { answer, limitReached } = await res.json();

    if (limitReached) {
      setAnswer({ type: "limit" });
    } else {
      setAnswer(parseResponse(answer));
    }

    setLoading(false);
  }

  //TYPEWRITER EFFECT
  function useTypewriter(text, speed = 20) {
    const [displayed, setDisplayed] = useState("");
    const [done, setDone] = useState(false);

    useEffect(() => {
      if (!text) return;
      setDisplayed("");
      setDone(false);
      let i = 0;
      const interval = setInterval(() => {
        setDisplayed(text.slice(0, i + 1));
        i++;
        if (i >= text.length) {
          clearInterval(interval);
          setDone(true);
        }
      }, speed);
      return () => clearInterval(interval);
    }, [text]);

    return { displayed, done };
  }

  // 4. TEXT ANSWER COMPONENT

  function TextAnswer({ content, links }) {
    const { displayed, done } = useTypewriter(content);

    return (
      <div>
        <span>{displayed}</span>
        {!done && <span className="cursor">▋</span>}

        {done && links?.length > 0 && (
          <div className="link-cards">
            {links.map((url) => (
              <LinkCard key={url} url={url} />
            ))}
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="chat-mode">
      <div className="flex flex-center">
        <h3>Pick a topic, and get some useful info</h3>{" "}
        <span
          class="metric-badge"
          title="This is a beta feature. Answers are generated by an AI model and may be inaccurate or incomplete. Always refer to the web mode for the most up-to-date and accurate information."
        >
          Beta
        </span>
      </div>
      <div className="chat-prompts">
        {PROMPTS.map((prompt) => (
          <button
            key={prompt.label}
            onClick={() => ask(prompt.label)}
            className="prompt-item"
          >
            <Image src={prompt.icon} alt="" width={16} height={16} />
            {prompt.label}
          </button>
        ))}
      </div>
      {loading && (
        <p className="chat-loading">
          <motion.svg
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 256 256"
            animate={{ rotate: 360 }}
            transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
            className="side-button"
          >
            <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm87.82,98.46c-28.34,20-49.57,14.68-71.87,4.39,20.06-14.19,38.86-32.21,39.53-67.11A87.92,87.92,0,0,1,215.82,122.46ZM167.11,49.19C170.24,83.71,155,99.44,135,113.61c-2.25-24.48-8.44-49.8-38.37-67.82a87.89,87.89,0,0,1,70.5,3.4ZM79.32,54.73c31.45,14.55,37.47,35.58,39.71,60-22.33-10.29-47.35-17.59-77.93-.68A88.18,88.18,0,0,1,79.32,54.73ZM40.18,133.54c28.34-20,49.57-14.68,71.87-4.39C92,143.34,73.19,161.36,72.52,196.26A87.92,87.92,0,0,1,40.18,133.54Zm48.71,73.27C85.76,172.29,101,156.56,121,142.39c2.25,24.48,8.44,49.8,38.37,67.82a87.89,87.89,0,0,1-70.5-3.4Zm87.79-5.54c-31.45-14.55-37.47-35.58-39.71-60,12.72,5.86,26.31,10.75,41.3,10.75,11.33,0,23.46-2.8,36.63-10.08A88.2,88.2,0,0,1,176.68,201.27Z" />
          </motion.svg>
        </p>
      )}
      {answer && !loading && (
        <div className="chat-answer">
          {answer.type === "limit" && (
            <p>
              <TextAnswer content="Currently there are no tokens left. Go back to portfolio mode." />
            </p>
          )}
          {answer.type === "timeline" && (
            <Timeline jobs={answer.jobs} summary={answer.summary} />
          )}
          {answer.type === "text" && (
            <TextAnswer content={answer.content} links={answer.links} />
          )}
        </div>
      )}
    </div>
  );
}
