const ToolboxList = [
  {
    name: "Miro",
    url: "https://miro.com",
    image: "/miro.png",
    category: "Collaboration",
  },
  {
    name: "Figma",
    url: "https://Figma.com",
    image: "/figma.png",
    category: "Design",
  },
  {
    name: "1.1.1.1.",
    url: "https://1.1.1.1/",
    image: "/1.png",
    category: "Security",
  },
  {
    name: "Things",
    url: "https://culturedcode.com/things/",
    image: "/things.png",
    category: "Productivity",
  },
  {
    name: "Notion",
    url: "https://notion.so",
    image: "/Notion.png",
    category: "Writing",
  },
  {
    name: "Spotify",
    url: "https://Spotify.com",
    image: "/spotify.png",
    category: "Productivity",
  },
  {
    name: "Github",
    url: "https://github.com",
    image: "/github.png",
    category: "Collaboration",
  },
  {
    name: "VSCO",
    url: "https://vsco.com",
    image: "/vsco.png",
    category: "Design",
  },
  {
    name: "BlockBear",
    url: "https://blockbear.com",
    image: "/bbear.png",
    category: "Security",
  },
  {
    name: "Twitter",
    url: "https://twitter.com",
    image: "/twitter.png",
    category: "Communication",
  },
  {
    name: "Dependabot",
    url: "https://dependabot.com",
    image: "/dpdbot.png",
    category: "Development",
  },
  {
    name: "Obsidian",
    url: "https://obsidian.md",
    image: "/obsidian.png",
    category: "Productivity",
  },
  {
    name: "Loom",
    url: "https://loom.com",
    image: "/loom.png",
    category: "Productivity",
  },
  {
    name: "Next.js",
    url: "https://nextjs.org",
    image: "/nextjs.png",
    category: "Development",
  },
  {
    name: "Vercel",
    url: "https://vercel.com",
    image: "/vercel.png",
    category: "Development",
  },
  {
    name: "Spark",
    url: "https://sparkmailapp.com",
    image: "/spark.png",
    category: "Productivity",
  },
  {
    name: "Terminal",
    url: "https://support.apple.com/guide/terminal/welcome/mac",
    image: "/terminal.png",
    category: "Development",
  },
  {
    name: "VScode",
    url: "https://code.visualstudio.com/",
    image: "/vscode.png",
    category: "Development",
  },
  {
    name: "Firefox Dev Edition",
    url: "https://www.mozilla.org/en-US/firefox/developer/",
    image: "/firefox-dev.png",
    category: "Productivity",
  },
  {
    name: "Google Chrome Canary",
    url: "https://www.google.com/chrome/canary/",
    image: "/ggc.png",
    category: "Development",
  },
  {
    name: "Protonmail",
    url: "https://protonmail.com/",
    image: "/proton.png",
    category: "Security",
  },
  {
    name: "Lockwise",
    url: "https://www.mozilla.org/en-US/firefox/lockwise/",
    image: "/lockwise.png",
    category: "Security",
  },
  {
    name: "Muzzle",
    url: "https://muzzleapp.com/",
    image: "/muzzle.png",
    category: "Productivity",
  },
  {
    name: "Kap",
    url: "https://getkap.co/",
    image: "/kap.png",
    category: "Productivity",
  },
  {
    name: "DuckDuckGo",
    url: "https://duckduckgo.com/",
    image: "/ddg.png",
    category: "Security",
  },
  {
    name: "Raycast",
    url: "https://raycast.com/",
    image: "/raycast.png",
    category: "Productivity",
  },
  {
    name: "CleanShot",
    url: "https://cleanshot.com/",
    image: "/clearshot.png",
    category: "Productivity",
  },
];

export default ToolboxList;
